name: 'build'

on:
  push:
    # Only used for build stage.
    branches:
    - main
    paths-ignore:
    - '*.md'
    - '*.png'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '*.md'
    - '*.png'
    types: [opened, synchronize, reopened] # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request

env:
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy.
        fetch-depth: 0

    - name: Install Temurin OpenJDK
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'temurin'
        architecture: x64

    - name: Cache SonarCloud Packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven Packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Maven Package # Using JVM mode.
      run: chmod +x ./mvnw && ./mvnw -DskipTests clean package

    - name: Maven Test and SonarCloud
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./mvnw verify sonar:sonar \
          -Dsonar.projectKey="StevenJDH_simple-ssl" \
          -Dsonar.organization="stevenjdh" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.login=$SONAR_TOKEN